FROM ollama/ollama:latest

ENV OLLAMA_KEEP_ALIVE=1h
RUN ollama serve & sleep 5 ; ollama pull nemotron-mini ; echo "kill ollama serve process" ; ps -ef | grep 'ollama serve' | grep -v grep | awk '{print $2}' | xargs -r kill -9
COPY llms/ollama/model_download.sh /custom-startup/model_download.sh

# Expose the Proper Port
EXPOSE 11434

CMD ["serve"]
