name: Mobile CI/CD Pipeline

on:
  push:
    branches: [main, develop]
    paths: ['expo/**']
  pull_request:
    branches: [main]
    paths: ['expo/**']

jobs:
  test:
    name: Test Mobile App
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./expo/ppal

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: expo/ppal/package-lock.json

    - name: Install dependencies
      run: npm ci

    - name: Run type checking
      run: npx tsc --noEmit

    - name: Run linting
      run: npx expo lint

    - name: Run tests
      run: npm test -- --coverage --watchAll=false

    - name: Upload coverage
      uses: codecov/codecov-action@v4
      with:
        file: ./expo/ppal/coverage/lcov.info
        flags: mobile
        name: mobile-coverage

  build-preview:
    name: Build Preview
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request'
    defaults:
      run:
        working-directory: ./expo/ppal

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: expo/ppal/package-lock.json

    - name: Set up Expo CLI
      run: npm install -g @expo/cli

    - name: Install dependencies
      run: npm ci

    - name: Build for preview
      run: npx expo export --platform all
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

  build-production:
    name: Build Production
    runs-on: ubuntu-latest
    needs: test
    if: github.ref == 'refs/heads/main'
    defaults:
      run:
        working-directory: ./expo/ppal

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'npm'
        cache-dependency-path: expo/ppal/package-lock.json

    - name: Set up Expo CLI
      run: npm install -g @expo/cli eas-cli

    - name: Install dependencies
      run: npm ci

    - name: Build iOS app
      run: eas build --platform ios --profile production --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}

    - name: Build Android app
      run: eas build --platform android --profile production --non-interactive
      env:
        EXPO_TOKEN: ${{ secrets.EXPO_TOKEN }}